config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  scope :users do
    post 'card_number_check', to: 'users#card_number_check'
  end

  resources :users do
    member do
      get 'pin'
      get 'main_screen'
      get 'take_cash'
      get 'put_cash'
      get 'transaction'
      post 'pin_check'
      post 'update_take_cash'
      post 'update_put_cash'
      post 'update_transaction'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  enum status: [:active, :blocked]
  enum authorization: [:unperformed, :performed]

  validates :card_number,   presence: true
  validates :pin,           presence: true
  validates :balance,       presence: true
  validates :attempts,      presence: true
  validates :status,        presence: true
  validates :authorization, presence: true
  validates :card_number,   numericality: true
  validates :pin,           numericality: true
  validates :balance,       numericality: { greater_than_or_equal_to: 0 }
  validates :attempts,      numericality: { greater_than_or_equal_to: 0 }
  validates :card_number,   length: { is: 16 }
  validates :pin,           length: { is: 4 }


  def correct_pin
    unlock! if active?
  end

  def incorrect_pin
    update_attributes(attempts: attempts + 1) unless block_required?
    block! if block_required?
  end

  def block_required?
    attempts >= 3
  end

  def reset_attempts
    update_attributes(attempts: 0)
  end

  def block!
    update_attributes(status: :blocked)
  end

  def unlock!
    reset_attempts
    update_attributes(status: :active)
  end

  def attempts_left
    3 - attempts
  end

  def authorized?
    authorization == 'performed'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method  :user

	protected

  def user
    @user ||= User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  before_action :user, only: [:pin, :main_screen]
  before_action :check_user, only: [:show, :take_cash, :put_cash, :transaction]
  before_action :unauthorize_user, only: [:show, :take_cash, :put_cash, :transaction]

  def pin
    @next_action = params[:next_action]
    render :pin
  end

  def pin_check
    if correct_pin?
      user.correct_pin
      user.performed!
      path = MAIN_PATHS[params[:next_action].to_sym] || 'main_screen_user_path'
      redirect_to eval(path), id: user.id
    else
      user.incorrect_pin
      redirect_to pin_user_path(user, incorrect_pin: "true", next_action: params[:next_action])
    end
  end

  def card_number_check
    @user = User.find_by(card_number: params[:user][:card_number])
    if @user
      redirect_to pin_user_path(@user)
    else
      redirect_to root_path invalid_card: "true"
    end
  end

  def update_take_cash
    if enough_money?
      user.update(balance: user.balance - user_params[:balance].to_i)
      redirect_to main_screen_user_path, notice: "Pleace, Take your money"
    else
      redirect_to main_screen_user_path, alert: "Error. Not enogh money"
    end
  end

  def update_put_cash
    user.update(balance: user.balance + user_params[:balance].to_i)
    redirect_to main_screen_user_path, notice: "Operation was successful"
  end

  def update_transaction
    if payee && enough_money?
      payee.update(balance: @payee.balance + user_params[:balance].to_i)
      user.update(balance: user.balance - user_params[:balance].to_i)
      redirect_to main_screen_user_path, notice: "Transaction was successful"
    else
      redirect_to main_screen_user_path, alert: "Error. Not enogh money" unless enough_money?
      redirect_to main_screen_user_path, alert: "Error. Wrong card number" unless payee
    end
  end

  private

  def payee
    @payee = User.find_by(card_number: user_params[:card_number])
  end

  def check_user
    redirect_to pin_user_path(user, next_action: action_name) unless user.authorized?
  end

  def unauthorize_user
    user.unperformed!
  end

  def user_params
    params.require(:user).permit(:balance, :card_number)
  end

  def enough_money?
    user.balance >= user_params[:balance].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then "alert alert-info"
    when 'success' then "alert alert-success"
    when 'error' then "alert alert-danger"
    when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  MAIN_PATHS = { show: 'user_path',
                 take_cash: 'take_cash_user_path',
                 put_cash: 'put_cash_user_path',
                 transaction: 'transaction_user_path' }

  def correct_pin?
    user.pin.to_s == params[:user][:pin]
  end
end

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    = csrf_meta_tags
    meta[http-equiv="Content-Type" content="text/html; charset=UTF-8"]
    meta[charset="utf-8"]
    meta[http-equiv="X-UA-Compatible" content="IE=edge"]
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag

    = favicon_link_tag 'favicon.ico'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    title
      | ATM
  body.h-100[id="#{controller_name.dasherize}-#{action_name.dasherize}"]
    = yield

app/views/users/index.html.slim
.main-content-container.container-fluid
  .row.no-gutters.h-100
    .col-md-4.col-md-offset-4.my-auto.auth-form
      .x_panel
        .x_title
          h5.auth-form__title.text-center.mb-4
            - if params[:invalid_card]
              | This card is invalid. Insert valid card:
            - else
              | Insert your card:
        .x_content
          = simple_form_for(:user, url: card_number_check_path, method: :post, html: { class: 'form-horizontal form-label-left' }) do |f|
            .item.form-group
              label.control-label.col-md-3.col-sm-3
                | Card number:
              .col-md-6.col-sm-6.col-xs-12
                = f.input :card_number, label: false, required: true, placeholder: 'Card number', input_html: { class: 'form-control' }
                .ln_solid
                .form-group.text-center
                  = f.submit 'Insert', class: 'btn-lg btn-success'
                .clearfix

app/views/users/main_screen.html.slim
.main-content-container.container-fluid
  .row.no-gutters.h-100
    .col-md-4.col-md-offset-4.my-auto.auth-form
      .x_panel.text-center
        .x_title
          h5.auth-form__title.text-center.mb-4
          | Main menu
        .x_content
          .form-horizontal.text-center
            - if @user.authorized?
              .item.form-group
                = button_to "Check cash", user_path, method: :get, class: 'btn btn-secondary btn-lg btn-block'
              .item.form-group
                = button_to "Take cash", take_cash_user_path, method: :get, class: 'btn btn-secondary btn-lg btn-block'
              .item.form-group
                = button_to "Put cash", put_cash_user_path, method: :get, class: 'btn btn-secondary btn-lg btn-block'
              .item.form-group
                = button_to "Transaction", transaction_user_path, method: :get, class: 'btn btn-secondary btn-lg btn-block'
            - else
              .item.form-group
                = button_to "Check cash", pin_user_path, method: :get, params: { next_action: :show }, class: 'btn btn-secondary btn-lg btn-block'
              .item.form-group
                = button_to "Take cash", pin_user_path, method: :get, params: { next_action: :take_cash }, class: 'btn btn-secondary btn-lg btn-block'
              .item.form-group
                = button_to "Put cash", pin_user_path, method: :get, params: { next_action: :put_cash }, class: 'btn btn-secondary btn-lg btn-block'
              .item.form-group
                = button_to "Transaction", pin_user_path, method: :get, params: { next_action: :transaction }, class: 'btn btn-secondary btn-lg btn-block'
            .item.form-group
              .ln_solid
              = button_to "Return card", root_path, method: :get, class: 'btn btn-secondary btn-lg btn-block btn-info'

app/views/users/pin.html.slim
.main-content-container.container-fluid
  .row.no-gutters.h-100
    .col-md-4.col-md-offset-4.my-auto.auth-form
      .x_panel
        .x_title
          - if @user.blocked?
            h5.auth-form__title.text-center.mb-4
              | Authorization failed! This card is blocked. Please contact the bank
          - else if params[:incorrect_pin]
            h5.auth-form__title.text-center.mb-4
              | Authorization failed! Incorrect PIN. Attempts left:&nbsp
              = @user.attempts_left
            - else
              h5.auth-form__title.text-center.mb-4
                | Authorization:
        .x_content
          = simple_form_for(:user, url: pin_check_user_path, method: :post, html: { class: 'form-horizontal form-label-left' }, defaults: { input_html: { class: 'form-control' } }) do |f|
            .item.form-group
              label.control-label.col-md-3.col-sm-3.col-xs-12
                | PIN:
              .col-md-6.col-sm-6.col-xs-12
                = f.input :pin, label: false, required: true, input_html: { type: 'password', value: nil }
                = hidden_field_tag(:next_action, @next_action)
                .ln_solid
                .form-group.text-center
                  = f.submit 'Submit', class: 'btn-success btn-lg'
                .clearfix
      .form-group.text-center
        = button_to "Return card", root_path, method: :get, class: 'btn-info btn-lg'

app/views/users/put_cash.html.slim
.main-content-container.container-fluid
  .row.no-gutters.h-100
    .col-md-4.col-md-offset-4.my-auto.auth-form
      .x_panel
        .x_title
          h4.auth-form__title.text-center.mb-4
            | Top-up card balance:
        .x_content
          = simple_form_for(:user, url: update_put_cash_user_path, method: :post, html: { class: 'form-horizontal form-label-left' }) do |f|
            .item.form-group
              label.control-label.col-md-3.col-sm-3.col-xs-12
                | Amount:
              .col-md-6.col-sm-6.col-xs-12
                = f.input :balance, label: false, input_html: { value: nil, class: 'form-control' }
                = hidden_field_tag(:subaction, 'put_cash')
                .ln_solid
                .form-group.text-center
                  = f.submit 'Submit', class: 'btn-success btn-sm'
                .clearfix
          .form-group.text-center
            = button_to "Back", main_screen_user_path, method: :get, class: 'btn btn-secondary btn-lg btn-block btn-info'

app/views/users/show.html.slim
.main-content-container.container-fluid
  .row.no-gutters.h-100
    .col-md-4.col-md-offset-4.my-auto.auth-form
      .x_panel
        .x_title
          h3.auth-form__title.text-center.mb-4
            | Your balance:&nbsp
            = @user.balance
            | &nbsp$
        .x_content
          .form-group.text-center
            = button_to "Back", main_screen_user_path, method: :get, class: 'btn btn-secondary btn-lg btn-block'
          .clearfix

app/views/users/take_cash.html.slim
.main-content-container.container-fluid
  .row.no-gutters.h-100
    .col-md-4.col-md-offset-4.my-auto.auth-form
      .x_panel
        .x_title
          h4.auth-form__title.text-center.mb-4
            | Select amount:
        .x_content
          table align='center'
            .form-horizontal.text-center
              .item.form-group
                  = button_to "10", update_take_cash_user_path, method: :post, params: { user: { balance: 10 }, subaction: :take_cash }, class: 'btn btn-secondary btn-lg btn-block'
              .item.form-group
                  = button_to "20", update_take_cash_user_path, method: :post, params: { user: { balance: 20 }, subaction: :take_cash }, class: 'btn btn-secondary btn-lg btn-block'
              .item.form-group
                = button_to "50", update_take_cash_user_path, method: :post, params: { user: { balance: 50 }, subaction: :take_cash }, class: 'btn btn-secondary btn-lg btn-block'
              .item.form-group
                = button_to "100", update_take_cash_user_path, method: :post, params: { user: { balance: 100 }, subaction: :take_cash }, class: 'btn btn-secondary btn-lg btn-block'
        .x_title
          h5.auth-form__title.text-center.mb-4
            | Or input by yourself:
        = simple_form_for(:user, url: update_take_cash_user_path, method: :post, html: { class: 'form-horizontal form-label-left' }) do |f|
          .item.form-group
            label.control-label.col-md-3.col-sm-3.col-xs-12
              | Amount:
            .col-md-6.col-sm-6.col-xs-12
              = f.input :balance, label: false, input_html: { value: nil, class: 'form-control' }
              = hidden_field_tag(:subaction, 'take_cash')
              .ln_solid
              .form-group.text-center
                = f.submit 'Submit', class: 'btn-success btn-sm'
              .clearfix
        .ln_solid
        = button_to "Back", main_screen_user_path, method: :get, class: 'btn btn-secondary btn-lg btn-block btn-info'
        .clearfix

app/views/users/transaction.html.slim
.main-content-container.container-fluid
  .row.no-gutters.h-100
    .col-md-4.col-md-offset-4.my-auto.auth-form
      .x_panel
        .x_title
          h4.auth-form__title.text-center.mb-4
            | Transfer money to another card
        .x_content
          = simple_form_for(:user, url: update_transaction_user_path, method: :post, html: { class: 'form-horizontal form-label-left' }, defaults: { input_html: { class: 'form-control' } }) do |f|
            .item.form-group
              label.control-label.col-md-3.col-sm-3.col-xs-12
                | Payee card number:
              .col-md-6.col-sm-6.col-xs-12
                = f.input :card_number, label: false, input_html: {value: nil}
            .item.form-group
              label.control-label.col-md-3.col-sm-3.col-xs-12
                | Amount:
              .col-md-6.col-sm-6.col-xs-12
                = f.input :balance, label: false, input_html: { value: nil }
                = hidden_field_tag(:subaction, 'transaction')
                .ln_solid
                .form-group.text-center
                  = f.submit 'Submit', class: 'btn-success btn-sm'
                .clearfix
          .form-group.text-center
            = button_to "Back", main_screen_user_path, method: :get, class: 'btn btn-secondary btn-lg btn-block btn-info'
          .clearfix